mimetypes:
  text/markdown: markdown
  text/plain: plain
  text/html: html
site:
  baseurl: http://pirata.cat
  language: ca
  name: Pirates de Catalunya
zas:
  deploy: .zas/deploy
  layout: .zas/layout.html
